name: 'Dependabot Deploy'
description: 'Automatically deploys PRs made by dependabot'
inputs:
  gitHubToken:
    description: 'Github token for current Action'
    required: true
  maxDeployVersion:
    description: 'The maximum difference in version which should be auto-deployed. `PATCH`, `MINOR`, `MAJOR`. Default `MINOR`'
    required: false
    default: 'MAJOR'
  deployOnlyInWorkingHours:
    description: 'If true then deploy will be skipped if the PR is created outside of working hours. Default `true`'
    required: false
    default: true
  timezone:
    description: 'Timezone defined https://momentjs.com/timezone/ used to verify if the current time is within the working hours. Default `Europe/Prague`'
    required: false
    default: 'Europe/Prague'
  deployDependencies:
    description: 'Defines what dependencies should be deployed. Either `dev` or `all`. Default `dev`'
    required: false
    default: dev
runs:
  using: 'node12'
  main: 'dist/index.js'
